[package]
name = "cefact-units-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Proc-macro for generating UN/CEFACT unit code types"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.3", features = ["full", "parsing", "extra-traits"] }
quote = "1.0.45"
proc-macro2 = "1.0.106"
calamine = "0.34.0"
heck = "0.5.0"
unicode-normalization = "0.1.25"
