[package]
name = "cefact-units"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "UN/CEFACT Recommendation No. 20 — units of measure"
readme = "../README.md"

[features]
default = []
serde = ["dep:serde"]
case-insensitive = []
generated-tests = []

[dependencies]
cefact-units-macros = { version = "0.1.0", path = "../cefact-units-macros" }
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0.151"
